var emojiShortName = {
  "🎨": "artist palette",
  "🎭": "performing arts",
  "🖼": "framed picture",
  "🧵": "thread",
  "🧶": "yarn",
  "🪡": "⊛ sewing needle",
  "🪢": "⊛ knot",
  "♟": "chess pawn",
  "♠": "spade suit",
  "♣": "club suit",
  "♥": "heart suit",
  "♦": "diamond suit",
  "⚽": "soccer ball",
  "⚾": "baseball",
  "⛳": "flag in hole",
  "⛸": "ice skate",
  "🀄": "mahjong red dragon",
  "🃏": "joker",
  "🎖": "military medal",
  "🎣": "fishing pole",
  "🎮": "video game",
  "🎯": "direct hit",
  "🎰": "slot machine",
  "🎱": "pool 8 ball",
  "🎲": "game die",
  "🎳": "bowling",
  "🎴": "flower playing cards",
  "🎽": "running shirt",
  "🎾": "tennis",
  "🎿": "skis",
  "🏀": "basketball",
  "🏅": "sports medal",
  "🏆": "trophy",
  "🏈": "american football",
  "🏉": "rugby football",
  "🏏": "cricket game",
  "🏐": "volleyball",
  "🏑": "field hockey",
  "🏒": "ice hockey",
  "🏓": "ping pong",
  "🏸": "badminton",
  "🔮": "crystal ball",
  "🕹": "joystick",
  "🛷": "sled",
  "🤿": "diving mask",
  "🥅": "goal net",
  "🥇": "1st place medal",
  "🥈": "2nd place medal",
  "🥉": "3rd place medal",
  "🥊": "boxing glove",
  "🥋": "martial arts uniform",
  "🥌": "curling stone",
  "🥍": "lacrosse",
  "🥎": "softball",
  "🥏": "flying disc",
  "🧩": "puzzle piece",
  "🧸": "teddy bear",
  "🧿": "nazar amulet",
  "🪀": "yo-yo",
  "🪁": "kite",
  "🪄": "⊛ magic wand",
  "🪅": "⊛ piñata",
  "🪆": "⊛ nesting dolls",
  "✨": "sparkles",
  "🎀": "ribbon",
  "🎁": "wrapped gift",
  "🎃": "jack-o-lantern",
  "🎄": "Christmas tree",
  "🎆": "fireworks",
  "🎇": "sparkler",
  "🎈": "balloon",
  "🎉": "party popper",
  "🎊": "confetti ball",
  "🎋": "tanabata tree",
  "🎍": "pine decoration",
  "🎎": "Japanese dolls",
  "🎏": "carp streamer",
  "🎐": "wind chime",
  "🎑": "moon viewing ceremony",
  "🎗": "reminder ribbon",
  "🎟": "admission tickets",
  "🎫": "ticket",
  "🧧": "red envelope",
  "🧨": "firecracker",
  "☘": "shamrock",
  "🌱": "seedling",
  "🌲": "evergreen tree",
  "🌳": "deciduous tree",
  "🌴": "palm tree",
  "🌵": "cactus",
  "🌷": "tulip",
  "🌸": "cherry blossom",
  "🌹": "rose",
  "🌺": "hibiscus",
  "🌻": "sunflower",
  "🌼": "blossom",
  "🌾": "sheaf of rice",
  "🌿": "herb",
  "🍀": "four leaf clover",
  "🍁": "maple leaf",
  "🍂": "fallen leaf",
  "🍃": "leaf fluttering in wind",
  "🏵": "rosette",
  "🐉": "dragon",
  "🐊": "crocodile",
  "🐋": "whale",
  "🐌": "snail",
  "🐍": "snake",
  "🐙": "octopus",
  "🐚": "spiral shell",
  "🐛": "bug",
  "🐜": "ant",
  "🐝": "honeybee",
  "🐞": "lady beetle",
  "🐟": "fish",
  "🐠": "tropical fish",
  "🐡": "blowfish",
  "🐢": "turtle",
  "🐬": "dolphin",
  "🐲": "dragon face",
  "🐳": "spouting whale",
  "🐸": "frog",
  "💐": "bouquet",
  "💮": "white flower",
  "🕷": "spider",
  "🕸": "spider web",
  "🥀": "wilted flower",
  "🦂": "scorpion",
  "🦈": "shark",
  "🦋": "butterfly",
  "🦎": "lizard",
  "🦕": "sauropod",
  "🦖": "T-Rex",
  "🦗": "cricket",
  "🦟": "mosquito",
  "🦠": "microbe",
  "🦭": "⊛ seal",
  "🪰": "⊛ fly",
  "🪱": "⊛ worm",
  "🪲": "⊛ beetle",
  "🪳": "⊛ cockroach",
  "🪴": "⊛ potted plant",
  "🐓": "rooster",
  "🐔": "chicken",
  "🐣": "hatching chick",
  "🐤": "baby chick",
  "🐥": "front-facing baby chick",
  "🐦": "bird",
  "🐧": "penguin",
  "🕊": "dove",
  "🦃": "turkey",
  "🦅": "eagle",
  "🦆": "duck",
  "🦉": "owl",
  "🦚": "peacock",
  "🦜": "parrot",
  "🦢": "swan",
  "🦤": "⊛ dodo",
  "🦩": "flamingo",
  "🪶": "⊛ feather",
  "🐀": "rat",
  "🐁": "mouse",
  "🐂": "ox",
  "🐃": "water buffalo",
  "🐄": "cow",
  "🐅": "tiger",
  "🐆": "leopard",
  "🐇": "rabbit",
  "🐈": "cat",
  "🐈‍⬛": "⊛ black cat",
  "🐎": "horse",
  "🐏": "ram",
  "🐐": "goat",
  "🐑": "ewe",
  "🐒": "monkey",
  "🐕": "dog",
  "🐕‍🦺": "service dog",
  "🐖": "pig",
  "🐗": "boar",
  "🐘": "elephant",
  "🐨": "koala",
  "🐩": "poodle",
  "🐪": "camel",
  "🐫": "two-hump camel",
  "🐭": "mouse face",
  "🐮": "cow face",
  "🐯": "tiger face",
  "🐰": "rabbit face",
  "🐱": "cat face",
  "🐴": "horse face",
  "🐵": "monkey face",
  "🐶": "dog face",
  "🐷": "pig face",
  "🐹": "hamster",
  "🐺": "wolf",
  "🐻": "bear",
  "🐻‍❄️": "⊛ polar bear",
  "🐼": "panda",
  "🐽": "pig nose",
  "🐾": "paw prints",
  "🐿": "chipmunk",
  "🦁": "lion",
  "🦄": "unicorn",
  "🦇": "bat",
  "🦊": "fox",
  "🦌": "deer",
  "🦍": "gorilla",
  "🦏": "rhinoceros",
  "🦒": "giraffe",
  "🦓": "zebra",
  "🦔": "hedgehog",
  "🦘": "kangaroo",
  "🦙": "llama",
  "🦛": "hippopotamus",
  "🦝": "raccoon",
  "🦡": "badger",
  "🦣": "⊛ mammoth",
  "🦥": "sloth",
  "🦦": "otter",
  "🦧": "orangutan",
  "🦨": "skunk",
  "🦫": "⊛ beaver",
  "🦬": "⊛ bison",
  "🦮": "guide dog",
  "🦰": "red hair",
  "🦱": "curly hair",
  "🦲": "bald",
  "🦳": "white hair",
  "🇦🇨": "flag: Ascension Island",
  "🇦🇩": "flag: Andorra",
  "🇦🇪": "flag: United Arab Emirates",
  "🇦🇫": "flag: Afghanistan",
  "🇦🇬": "flag: Antigua & Barbuda",
  "🇦🇮": "flag: Anguilla",
  "🇦🇱": "flag: Albania",
  "🇦🇲": "flag: Armenia",
  "🇦🇴": "flag: Angola",
  "🇦🇶": "flag: Antarctica",
  "🇦🇷": "flag: Argentina",
  "🇦🇸": "flag: American Samoa",
  "🇦🇹": "flag: Austria",
  "🇦🇺": "flag: Australia",
  "🇦🇼": "flag: Aruba",
  "🇦🇽": "flag: Åland Islands",
  "🇦🇿": "flag: Azerbaijan",
  "🇧🇦": "flag: Bosnia & Herzegovina",
  "🇧🇧": "flag: Barbados",
  "🇧🇩": "flag: Bangladesh",
  "🇧🇪": "flag: Belgium",
  "🇧🇫": "flag: Burkina Faso",
  "🇧🇬": "flag: Bulgaria",
  "🇧🇭": "flag: Bahrain",
  "🇧🇮": "flag: Burundi",
  "🇧🇯": "flag: Benin",
  "🇧🇱": "flag: St. Barthélemy",
  "🇧🇲": "flag: Bermuda",
  "🇧🇳": "flag: Brunei",
  "🇧🇴": "flag: Bolivia",
  "🇧🇶": "flag: Caribbean Netherlands",
  "🇧🇷": "flag: Brazil",
  "🇧🇸": "flag: Bahamas",
  "🇧🇹": "flag: Bhutan",
  "🇧🇻": "flag: Bouvet Island",
  "🇧🇼": "flag: Botswana",
  "🇧🇾": "flag: Belarus",
  "🇧🇿": "flag: Belize",
  "🇨🇦": "flag: Canada",
  "🇨🇨": "flag: Cocos (Keeling) Islands",
  "🇨🇩": "flag: Congo - Kinshasa",
  "🇨🇫": "flag: Central African Republic",
  "🇨🇬": "flag: Congo - Brazzaville",
  "🇨🇭": "flag: Switzerland",
  "🇨🇮": "flag: Côte d’Ivoire",
  "🇨🇰": "flag: Cook Islands",
  "🇨🇱": "flag: Chile",
  "🇨🇲": "flag: Cameroon",
  "🇨🇳": "flag: China",
  "🇨🇴": "flag: Colombia",
  "🇨🇵": "flag: Clipperton Island",
  "🇨🇷": "flag: Costa Rica",
  "🇨🇺": "flag: Cuba",
  "🇨🇻": "flag: Cape Verde",
  "🇨🇼": "flag: Curaçao",
  "🇨🇽": "flag: Christmas Island",
  "🇨🇾": "flag: Cyprus",
  "🇨🇿": "flag: Czechia",
  "🇩🇪": "flag: Germany",
  "🇩🇬": "flag: Diego Garcia",
  "🇩🇯": "flag: Djibouti",
  "🇩🇰": "flag: Denmark",
  "🇩🇲": "flag: Dominica",
  "🇩🇴": "flag: Dominican Republic",
  "🇩🇿": "flag: Algeria",
  "🇪🇦": "flag: Ceuta & Melilla",
  "🇪🇨": "flag: Ecuador",
  "🇪🇪": "flag: Estonia",
  "🇪🇬": "flag: Egypt",
  "🇪🇭": "flag: Western Sahara",
  "🇪🇷": "flag: Eritrea",
  "🇪🇸": "flag: Spain",
  "🇪🇹": "flag: Ethiopia",
  "🇪🇺": "flag: European Union",
  "🇫🇮": "flag: Finland",
  "🇫🇯": "flag: Fiji",
  "🇫🇰": "flag: Falkland Islands",
  "🇫🇲": "flag: Micronesia",
  "🇫🇴": "flag: Faroe Islands",
  "🇫🇷": "flag: France",
  "🇬🇦": "flag: Gabon",
  "🇬🇧": "flag: United Kingdom",
  "🇬🇩": "flag: Grenada",
  "🇬🇪": "flag: Georgia",
  "🇬🇫": "flag: French Guiana",
  "🇬🇬": "flag: Guernsey",
  "🇬🇭": "flag: Ghana",
  "🇬🇮": "flag: Gibraltar",
  "🇬🇱": "flag: Greenland",
  "🇬🇲": "flag: Gambia",
  "🇬🇳": "flag: Guinea",
  "🇬🇵": "flag: Guadeloupe",
  "🇬🇶": "flag: Equatorial Guinea",
  "🇬🇷": "flag: Greece",
  "🇬🇸": "flag: South Georgia & South Sandwich Islands",
  "🇬🇹": "flag: Guatemala",
  "🇬🇺": "flag: Guam",
  "🇬🇼": "flag: Guinea-Bissau",
  "🇬🇾": "flag: Guyana",
  "🇭🇰": "flag: Hong Kong SAR China",
  "🇭🇲": "flag: Heard & McDonald Islands",
  "🇭🇳": "flag: Honduras",
  "🇭🇷": "flag: Croatia",
  "🇭🇹": "flag: Haiti",
  "🇭🇺": "flag: Hungary",
  "🇮🇨": "flag: Canary Islands",
  "🇮🇩": "flag: Indonesia",
  "🇮🇪": "flag: Ireland",
  "🇮🇱": "flag: Israel",
  "🇮🇲": "flag: Isle of Man",
  "🇮🇳": "flag: India",
  "🇮🇴": "flag: British Indian Ocean Territory",
  "🇮🇶": "flag: Iraq",
  "🇮🇷": "flag: Iran",
  "🇮🇸": "flag: Iceland",
  "🇮🇹": "flag: Italy",
  "🇯🇪": "flag: Jersey",
  "🇯🇲": "flag: Jamaica",
  "🇯🇴": "flag: Jordan",
  "🇯🇵": "flag: Japan",
  "🇰🇪": "flag: Kenya",
  "🇰🇬": "flag: Kyrgyzstan",
  "🇰🇭": "flag: Cambodia",
  "🇰🇮": "flag: Kiribati",
  "🇰🇲": "flag: Comoros",
  "🇰🇳": "flag: St. Kitts & Nevis",
  "🇰🇵": "flag: North Korea",
  "🇰🇷": "flag: South Korea",
  "🇰🇼": "flag: Kuwait",
  "🇰🇾": "flag: Cayman Islands",
  "🇰🇿": "flag: Kazakhstan",
  "🇱🇦": "flag: Laos",
  "🇱🇧": "flag: Lebanon",
  "🇱🇨": "flag: St. Lucia",
  "🇱🇮": "flag: Liechtenstein",
  "🇱🇰": "flag: Sri Lanka",
  "🇱🇷": "flag: Liberia",
  "🇱🇸": "flag: Lesotho",
  "🇱🇹": "flag: Lithuania",
  "🇱🇺": "flag: Luxembourg",
  "🇱🇻": "flag: Latvia",
  "🇱🇾": "flag: Libya",
  "🇲🇦": "flag: Morocco",
  "🇲🇨": "flag: Monaco",
  "🇲🇩": "flag: Moldova",
  "🇲🇪": "flag: Montenegro",
  "🇲🇫": "flag: St. Martin",
  "🇲🇬": "flag: Madagascar",
  "🇲🇭": "flag: Marshall Islands",
  "🇲🇰": "flag: North Macedonia",
  "🇲🇱": "flag: Mali",
  "🇲🇲": "flag: Myanmar (Burma)",
  "🇲🇳": "flag: Mongolia",
  "🇲🇴": "flag: Macao SAR China",
  "🇲🇵": "flag: Northern Mariana Islands",
  "🇲🇶": "flag: Martinique",
  "🇲🇷": "flag: Mauritania",
  "🇲🇸": "flag: Montserrat",
  "🇲🇹": "flag: Malta",
  "🇲🇺": "flag: Mauritius",
  "🇲🇻": "flag: Maldives",
  "🇲🇼": "flag: Malawi",
  "🇲🇽": "flag: Mexico",
  "🇲🇾": "flag: Malaysia",
  "🇲🇿": "flag: Mozambique",
  "🇳🇦": "flag: Namibia",
  "🇳🇨": "flag: New Caledonia",
  "🇳🇪": "flag: Niger",
  "🇳🇫": "flag: Norfolk Island",
  "🇳🇬": "flag: Nigeria",
  "🇳🇮": "flag: Nicaragua",
  "🇳🇱": "flag: Netherlands",
  "🇳🇴": "flag: Norway",
  "🇳🇵": "flag: Nepal",
  "🇳🇷": "flag: Nauru",
  "🇳🇺": "flag: Niue",
  "🇳🇿": "flag: New Zealand",
  "🇴🇲": "flag: Oman",
  "🇵🇦": "flag: Panama",
  "🇵🇪": "flag: Peru",
  "🇵🇫": "flag: French Polynesia",
  "🇵🇬": "flag: Papua New Guinea",
  "🇵🇭": "flag: Philippines",
  "🇵🇰": "flag: Pakistan",
  "🇵🇱": "flag: Poland",
  "🇵🇲": "flag: St. Pierre & Miquelon",
  "🇵🇳": "flag: Pitcairn Islands",
  "🇵🇷": "flag: Puerto Rico",
  "🇵🇸": "flag: Palestinian Territories",
  "🇵🇹": "flag: Portugal",
  "🇵🇼": "flag: Palau",
  "🇵🇾": "flag: Paraguay",
  "🇶🇦": "flag: Qatar",
  "🇷🇪": "flag: Réunion",
  "🇷🇴": "flag: Romania",
  "🇷🇸": "flag: Serbia",
  "🇷🇺": "flag: Russia",
  "🇷🇼": "flag: Rwanda",
  "🇸🇦": "flag: Saudi Arabia",
  "🇸🇧": "flag: Solomon Islands",
  "🇸🇨": "flag: Seychelles",
  "🇸🇩": "flag: Sudan",
  "🇸🇪": "flag: Sweden",
  "🇸🇬": "flag: Singapore",
  "🇸🇭": "flag: St. Helena",
  "🇸🇮": "flag: Slovenia",
  "🇸🇯": "flag: Svalbard & Jan Mayen",
  "🇸🇰": "flag: Slovakia",
  "🇸🇱": "flag: Sierra Leone",
  "🇸🇲": "flag: San Marino",
  "🇸🇳": "flag: Senegal",
  "🇸🇴": "flag: Somalia",
  "🇸🇷": "flag: Suriname",
  "🇸🇸": "flag: South Sudan",
  "🇸🇹": "flag: São Tomé & Príncipe",
  "🇸🇻": "flag: El Salvador",
  "🇸🇽": "flag: Sint Maarten",
  "🇸🇾": "flag: Syria",
  "🇸🇿": "flag: Eswatini",
  "🇹🇦": "flag: Tristan da Cunha",
  "🇹🇨": "flag: Turks & Caicos Islands",
  "🇹🇩": "flag: Chad",
  "🇹🇫": "flag: French Southern Territories",
  "🇹🇬": "flag: Togo",
  "🇹🇭": "flag: Thailand",
  "🇹🇯": "flag: Tajikistan",
  "🇹🇰": "flag: Tokelau",
  "🇹🇱": "flag: Timor-Leste",
  "🇹🇲": "flag: Turkmenistan",
  "🇹🇳": "flag: Tunisia",
  "🇹🇴": "flag: Tonga",
  "🇹🇷": "flag: Turkey",
  "🇹🇹": "flag: Trinidad & Tobago",
  "🇹🇻": "flag: Tuvalu",
  "🇹🇼": "flag: Taiwan",
  "🇹🇿": "flag: Tanzania",
  "🇺🇦": "flag: Ukraine",
  "🇺🇬": "flag: Uganda",
  "🇺🇲": "flag: U.S. Outlying Islands",
  "🇺🇳": "flag: United Nations",
  "🇺🇸": "flag: United States",
  "🇺🇾": "flag: Uruguay",
  "🇺🇿": "flag: Uzbekistan",
  "🇻🇦": "flag: Vatican City",
  "🇻🇨": "flag: St. Vincent & Grenadines",
  "🇻🇪": "flag: Venezuela",
  "🇻🇬": "flag: British Virgin Islands",
  "🇻🇮": "flag: U.S. Virgin Islands",
  "🇻🇳": "flag: Vietnam",
  "🇻🇺": "flag: Vanuatu",
  "🇼🇫": "flag: Wallis & Futuna",
  "🇼🇸": "flag: Samoa",
  "🇽🇰": "flag: Kosovo",
  "🇾🇪": "flag: Yemen",
  "🇾🇹": "flag: Mayotte",
  "🇿🇦": "flag: South Africa",
  "🇿🇲": "flag: Zambia",
  "🇿🇼": "flag: Zimbabwe",
  "🏴󠁧󠁢󠁥󠁮󠁧󠁿": "flag: England",
  "🏴󠁧󠁢󠁳󠁣󠁴󠁿": "flag: Scotland",
  "🏴󠁧󠁢󠁷󠁬󠁳󠁿": "flag: Wales",
  "🎌": "crossed flags",
  "🏁": "chequered flag",
  "🏳": "white flag",
  "🏳️‍⚧️": "⊛ transgender flag",
  "🏳️‍🌈": "rainbow flag",
  "🏴": "black flag",
  "🏴‍☠️": "pirate flag",
  "🚩": "triangular flag",
  "🍴": "fork and knife",
  "🍽": "fork and knife with plate",
  "🏺": "amphora",
  "🔪": "kitchen knife",
  "🥄": "spoon",
  "🥢": "chopsticks",
  "☕": "hot beverage",
  "🍵": "teacup without handle",
  "🍶": "sake",
  "🍷": "wine glass",
  "🍸": "cocktail glass",
  "🍹": "tropical drink",
  "🍺": "beer mug",
  "🍻": "clinking beer mugs",
  "🍼": "baby bottle",
  "🍾": "bottle with popping cork",
  "🥂": "clinking glasses",
  "🥃": "tumbler glass",
  "🥛": "glass of milk",
  "🥤": "cup with straw",
  "🧃": "beverage box",
  "🧉": "mate",
  "🧊": "ice",
  "🧋": "⊛ bubble tea",
  "🫖": "⊛ teapot",
  "🍘": "rice cracker",
  "🍙": "rice ball",
  "🍚": "cooked rice",
  "🍛": "curry rice",
  "🍜": "steaming bowl",
  "🍝": "spaghetti",
  "🍠": "roasted sweet potato",
  "🍡": "dango",
  "🍢": "oden",
  "🍣": "sushi",
  "🍤": "fried shrimp",
  "🍥": "fish cake with swirl",
  "🍦": "soft ice cream",
  "🍧": "shaved ice",
  "🍨": "ice cream",
  "🍩": "doughnut",
  "🍪": "cookie",
  "🍫": "chocolate bar",
  "🍬": "candy",
  "🍭": "lollipop",
  "🍮": "custard",
  "🍯": "honey pot",
  "🍰": "shortcake",
  "🍱": "bento box",
  "🎂": "birthday cake",
  "🥟": "dumpling",
  "🥠": "fortune cookie",
  "🥡": "takeout box",
  "🥧": "pie",
  "🥮": "moon cake",
  "🦀": "crab",
  "🦐": "shrimp",
  "🦑": "squid",
  "🦞": "lobster",
  "🦪": "oyster",
  "🧁": "cupcake",
  "🌭": "hot dog",
  "🌮": "taco",
  "🌯": "burrito",
  "🌰": "chestnut",
  "🌶": "hot pepper",
  "🌽": "ear of corn",
  "🍄": "mushroom",
  "🍅": "tomato",
  "🍆": "eggplant",
  "🍇": "grapes",
  "🍈": "melon",
  "🍉": "watermelon",
  "🍊": "tangerine",
  "🍋": "lemon",
  "🍌": "banana",
  "🍍": "pineapple",
  "🍎": "red apple",
  "🍏": "green apple",
  "🍐": "pear",
  "🍑": "peach",
  "🍒": "cherries",
  "🍓": "strawberry",
  "🍔": "hamburger",
  "🍕": "pizza",
  "🍖": "meat on bone",
  "🍗": "poultry leg",
  "🍞": "bread",
  "🍟": "french fries",
  "🍲": "pot of food",
  "🍳": "cooking",
  "🍿": "popcorn",
  "🥐": "croissant",
  "🥑": "avocado",
  "🥒": "cucumber",
  "🥓": "bacon",
  "🥔": "potato",
  "🥕": "carrot",
  "🥖": "baguette bread",
  "🥗": "green salad",
  "🥘": "shallow pan of food",
  "🥙": "stuffed flatbread",
  "🥚": "egg",
  "🥜": "peanuts",
  "🥝": "kiwi fruit",
  "🥞": "pancakes",
  "🥣": "bowl with spoon",
  "🥥": "coconut",
  "🥦": "broccoli",
  "🥨": "pretzel",
  "🥩": "cut of meat",
  "🥪": "sandwich",
  "🥫": "canned food",
  "🥬": "leafy green",
  "🥭": "mango",
  "🥯": "bagel",
  "🧀": "cheese wedge",
  "🧂": "salt",
  "🧄": "garlic",
  "🧅": "onion",
  "🧆": "falafel",
  "🧇": "waffle",
  "🧈": "butter",
  "🫐": "⊛ blueberries",
  "🫑": "⊛ bell pepper",
  "🫒": "⊛ olive",
  "🫓": "⊛ flatbread",
  "🫔": "⊛ tamale",
  "🫕": "⊛ fondue",
  "⚒": "hammer and pick",
  "⚔": "crossed swords",
  "⚖": "balance scale",
  "⚗": "alembic",
  "⚙": "gear",
  "⚰": "coffin",
  "⚱": "funeral urn",
  "⛏": "pick",
  "⛓": "chains",
  "✂": "scissors",
  "✉": "envelope",
  "✏": "pencil",
  "✒": "black nib",
  "🏷": "label",
  "🏹": "bow and arrow",
  "💉": "syringe",
  "💊": "pill",
  "💰": "money bag",
  "💳": "credit card",
  "💴": "yen banknote",
  "💵": "dollar banknote",
  "💶": "euro banknote",
  "💷": "pound banknote",
  "💸": "money with wings",
  "💹": "chart increasing with yen",
  "💼": "briefcase",
  "📁": "file folder",
  "📂": "open file folder",
  "📃": "page with curl",
  "📄": "page facing up",
  "📅": "calendar",
  "📆": "tear-off calendar",
  "📇": "card index",
  "📈": "chart increasing",
  "📉": "chart decreasing",
  "📊": "bar chart",
  "📋": "clipboard",
  "📌": "pushpin",
  "📍": "round pushpin",
  "📎": "paperclip",
  "📏": "straight ruler",
  "📐": "triangular ruler",
  "📑": "bookmark tabs",
  "📒": "ledger",
  "📓": "notebook",
  "📔": "notebook with decorative cover",
  "📕": "closed book",
  "📖": "open book",
  "📗": "green book",
  "📘": "blue book",
  "📙": "orange book",
  "📚": "books",
  "📜": "scroll",
  "📝": "memo",
  "📡": "satellite antenna",
  "📤": "outbox tray",
  "📥": "inbox tray",
  "📦": "package",
  "📧": "e-mail",
  "📨": "incoming envelope",
  "📩": "envelope with arrow",
  "📪": "closed mailbox with lowered flag",
  "📫": "closed mailbox with raised flag",
  "📬": "open mailbox with raised flag",
  "📭": "open mailbox with lowered flag",
  "📮": "postbox",
  "📰": "newspaper",
  "🔏": "locked with pen",
  "🔐": "locked with key",
  "🔑": "key",
  "🔒": "locked",
  "🔓": "unlocked",
  "🔖": "bookmark",
  "🔗": "link",
  "🔧": "wrench",
  "🔨": "hammer",
  "🔩": "nut and bolt",
  "🔫": "pistol",
  "🔬": "microscope",
  "🔭": "telescope",
  "🖇": "linked paperclips",
  "🖊": "pen",
  "🖋": "fountain pen",
  "🖌": "paintbrush",
  "🖍": "crayon",
  "🗂": "card index dividers",
  "🗃": "card file box",
  "🗄": "file cabinet",
  "🗑": "wastebasket",
  "🗒": "spiral notepad",
  "🗓": "spiral calendar",
  "🗜": "clamp",
  "🗝": "old key",
  "🗞": "rolled-up newspaper",
  "🗡": "dagger",
  "🗳": "ballot box with ballot",
  "🗿": "moai",
  "🚪": "door",
  "🚬": "cigarette",
  "🚽": "toilet",
  "🚿": "shower",
  "🛁": "bathtub",
  "🛋": "couch and lamp",
  "🛏": "bed",
  "🛒": "shopping cart",
  "🛗": "⊛ elevator",
  "🛠": "hammer and wrench",
  "🛡": "shield",
  "🦯": "white cane",
  "🧪": "test tube",
  "🧫": "petri dish",
  "🧬": "dna",
  "🧯": "fire extinguisher",
  "🧰": "toolbox",
  "🧲": "magnet",
  "🧴": "lotion bottle",
  "🧷": "safety pin",
  "🧹": "broom",
  "🧺": "basket",
  "🧻": "roll of paper",
  "🧼": "soap",
  "🧽": "sponge",
  "🧾": "receipt",
  "🩸": "drop of blood",
  "🩹": "adhesive bandage",
  "🩺": "stethoscope",
  "🪃": "⊛ boomerang",
  "🪑": "chair",
  "🪒": "razor",
  "🪓": "axe",
  "🪙": "⊛ coin",
  "🪚": "⊛ carpentry saw",
  "🪛": "⊛ screwdriver",
  "🪜": "⊛ ladder",
  "🪝": "⊛ hook",
  "🪞": "⊛ mirror",
  "🪟": "⊛ window",
  "🪠": "⊛ plunger",
  "🪣": "⊛ bucket",
  "🪤": "⊛ mouse trap",
  "🪥": "⊛ toothbrush",
  "🪦": "⊛ headstone",
  "🪧": "⊛ placard",
  "⌨": "keyboard",
  "☎": "telephone",
  "⛑": "rescue worker’s helmet",
  "🎒": "backpack",
  "🎓": "graduation cap",
  "🎙": "studio microphone",
  "🎚": "level slider",
  "🎛": "control knobs",
  "🎞": "film frames",
  "🎤": "microphone",
  "🎥": "movie camera",
  "🎧": "headphone",
  "🎩": "top hat",
  "🎬": "clapper board",
  "🎵": "musical note",
  "🎶": "musical notes",
  "🎷": "saxophone",
  "🎸": "guitar",
  "🎹": "musical keyboard",
  "🎺": "trumpet",
  "🎻": "violin",
  "🎼": "musical score",
  "🏮": "red paper lantern",
  "👑": "crown",
  "👒": "woman’s hat",
  "👓": "glasses",
  "👔": "necktie",
  "👕": "t-shirt",
  "👖": "jeans",
  "👗": "dress",
  "👘": "kimono",
  "👙": "bikini",
  "👚": "woman’s clothes",
  "👛": "purse",
  "👜": "handbag",
  "👝": "clutch bag",
  "👞": "man’s shoe",
  "👟": "running shoe",
  "👠": "high-heeled shoe",
  "👡": "woman’s sandal",
  "👢": "woman’s boot",
  "💄": "lipstick",
  "💍": "ring",
  "💎": "gem stone",
  "💡": "light bulb",
  "💻": "laptop",
  "💽": "computer disk",
  "💾": "floppy disk",
  "💿": "optical disk",
  "📀": "dvd",
  "📞": "telephone receiver",
  "📟": "pager",
  "📠": "fax machine",
  "📢": "loudspeaker",
  "📣": "megaphone",
  "📯": "postal horn",
  "📱": "mobile phone",
  "📲": "mobile phone with arrow",
  "📷": "camera",
  "📸": "camera with flash",
  "📹": "video camera",
  "📺": "television",
  "📻": "radio",
  "📼": "videocassette",
  "📽": "film projector",
  "📿": "prayer beads",
  "🔇": "muted speaker",
  "🔈": "speaker low volume",
  "🔉": "speaker medium volume",
  "🔊": "speaker high volume",
  "🔋": "battery",
  "🔌": "electric plug",
  "🔍": "magnifying glass tilted left",
  "🔎": "magnifying glass tilted right",
  "🔔": "bell",
  "🔕": "bell with slash",
  "🔦": "flashlight",
  "🕯": "candle",
  "🕶": "sunglasses",
  "🖥": "desktop computer",
  "🖨": "printer",
  "🖱": "computer mouse",
  "🖲": "trackball",
  "🛍": "shopping bags",
  "🥁": "drum",
  "🥻": "sari",
  "🥼": "lab coat",
  "🥽": "goggles",
  "🥾": "hiking boot",
  "🥿": "flat shoe",
  "🦺": "safety vest",
  "🧢": "billed cap",
  "🧣": "scarf",
  "🧤": "gloves",
  "🧥": "coat",
  "🧦": "socks",
  "🧮": "abacus",
  "🩰": "ballet shoes",
  "🩱": "one-piece swimsuit",
  "🩲": "briefs",
  "🩳": "shorts",
  "🩴": "⊛ thong sandal",
  "🪔": "diya lamp",
  "🪕": "banjo",
  "🪖": "⊛ military helmet",
  "🪗": "⊛ accordion",
  "🪘": "⊛ long drum",
  "⛷": "skier",
  "⛹": "person bouncing ball",
  "⛹️‍♀️": "woman bouncing ball",
  "⛹️‍♂️": "man bouncing ball",
  "🎅": "Santa Claus",
  "🏂": "snowboarder",
  "🏃": "person running",
  "🏃‍♀️": "woman running",
  "🏃‍♂️": "man running",
  "🏄": "person surfing",
  "🏄‍♀️": "woman surfing",
  "🏄‍♂️": "man surfing",
  "🏇": "horse racing",
  "🏊": "person swimming",
  "🏊‍♀️": "woman swimming",
  "🏊‍♂️": "man swimming",
  "🏋": "person lifting weights",
  "🏋️‍♀️": "woman lifting weights",
  "🏋️‍♂️": "man lifting weights",
  "🏌": "person golfing",
  "🏌️‍♀️": "woman golfing",
  "🏌️‍♂️": "man golfing",
  "👀": "eyes",
  "👁": "eye",
  "👂": "ear",
  "👃": "nose",
  "👄": "mouth",
  "👅": "tongue",
  "👣": "footprints",
  "👤": "bust in silhouette",
  "👥": "busts in silhouette",
  "👦": "boy",
  "👧": "girl",
  "👨": "man",
  "👨‍⚕️": "man health worker",
  "👨‍⚖️": "man judge",
  "👨‍✈️": "man pilot",
  "👨‍❤️‍👨": "couple with heart: man, man",
  "👨‍❤️‍💋‍👨": "kiss: man, man",
  "👨‍🌾": "man farmer",
  "👨‍🍳": "man cook",
  "👨‍🍼": "⊛ man feeding baby",
  "👨‍🎓": "man student",
  "👨‍🎤": "man singer",
  "👨‍🎨": "man artist",
  "👨‍🏫": "man teacher",
  "👨‍🏭": "man factory worker",
  "👨‍👦": "family: man, boy",
  "👨‍👦‍👦": "family: man, boy, boy",
  "👨‍👧": "family: man, girl",
  "👨‍👧‍👦": "family: man, girl, boy",
  "👨‍👧‍👧": "family: man, girl, girl",
  "👨‍👨‍👦": "family: man, man, boy",
  "👨‍👨‍👦‍👦": "family: man, man, boy, boy",
  "👨‍👨‍👧": "family: man, man, girl",
  "👨‍👨‍👧‍👦": "family: man, man, girl, boy",
  "👨‍👨‍👧‍👧": "family: man, man, girl, girl",
  "👨‍👩‍👦": "family: man, woman, boy",
  "👨‍👩‍👦‍👦": "family: man, woman, boy, boy",
  "👨‍👩‍👧": "family: man, woman, girl",
  "👨‍👩‍👧‍👦": "family: man, woman, girl, boy",
  "👨‍👩‍👧‍👧": "family: man, woman, girl, girl",
  "👨‍💻": "man technologist",
  "👨‍💼": "man office worker",
  "👨‍🔧": "man mechanic",
  "👨‍🔬": "man scientist",
  "👨‍🚀": "man astronaut",
  "👨‍🚒": "man firefighter",
  "👨‍🦯": "man with white cane",
  "👨‍🦰": "man: red hair",
  "👨‍🦱": "man: curly hair",
  "👨‍🦲": "man: bald",
  "👨‍🦳": "man: white hair",
  "👨‍🦼": "man in motorized wheelchair",
  "👨‍🦽": "man in manual wheelchair",
  "👩": "woman",
  "👩‍⚕️": "woman health worker",
  "👩‍⚖️": "woman judge",
  "👩‍✈️": "woman pilot",
  "👩‍❤️‍👨": "couple with heart: woman, man",
  "👩‍❤️‍👩": "couple with heart: woman, woman",
  "👩‍❤️‍💋‍👨": "kiss: woman, man",
  "👩‍❤️‍💋‍👩": "kiss: woman, woman",
  "👩‍🌾": "woman farmer",
  "👩‍🍳": "woman cook",
  "👩‍🍼": "⊛ woman feeding baby",
  "👩‍🎓": "woman student",
  "👩‍🎤": "woman singer",
  "👩‍🎨": "woman artist",
  "👩‍🏫": "woman teacher",
  "👩‍🏭": "woman factory worker",
  "👩‍👦": "family: woman, boy",
  "👩‍👦‍👦": "family: woman, boy, boy",
  "👩‍👧": "family: woman, girl",
  "👩‍👧‍👦": "family: woman, girl, boy",
  "👩‍👧‍👧": "family: woman, girl, girl",
  "👩‍👩‍👦": "family: woman, woman, boy",
  "👩‍👩‍👦‍👦": "family: woman, woman, boy, boy",
  "👩‍👩‍👧": "family: woman, woman, girl",
  "👩‍👩‍👧‍👦": "family: woman, woman, girl, boy",
  "👩‍👩‍👧‍👧": "family: woman, woman, girl, girl",
  "👩‍💻": "woman technologist",
  "👩‍💼": "woman office worker",
  "👩‍🔧": "woman mechanic",
  "👩‍🔬": "woman scientist",
  "👩‍🚀": "woman astronaut",
  "👩‍🚒": "woman firefighter",
  "👩‍🦯": "woman with white cane",
  "👩‍🦰": "woman: red hair",
  "👩‍🦱": "woman: curly hair",
  "👩‍🦲": "woman: bald",
  "👩‍🦳": "woman: white hair",
  "👩‍🦼": "woman in motorized wheelchair",
  "👩‍🦽": "woman in manual wheelchair",
  "👪": "family",
  "👫": "woman and man holding hands",
  "👬": "men holding hands",
  "👭": "women holding hands",
  "👮": "police officer",
  "👮‍♀️": "woman police officer",
  "👮‍♂️": "man police officer",
  "👯": "people with bunny ears",
  "👯‍♀️": "women with bunny ears",
  "👯‍♂️": "men with bunny ears",
  "👰": "person with veil",
  "👰‍♀️": "⊛ woman with veil",
  "👰‍♂️": "⊛ man with veil",
  "👱": "person: blond hair",
  "👱‍♀️": "woman: blond hair",
  "👱‍♂️": "man: blond hair",
  "👲": "person with skullcap",
  "👳": "person wearing turban",
  "👳‍♀️": "woman wearing turban",
  "👳‍♂️": "man wearing turban",
  "👴": "old man",
  "👵": "old woman",
  "👶": "baby",
  "👷": "construction worker",
  "👷‍♀️": "woman construction worker",
  "👷‍♂️": "man construction worker",
  "👸": "princess",
  "👼": "baby angel",
  "💁": "person tipping hand",
  "💁‍♀️": "woman tipping hand",
  "💁‍♂️": "man tipping hand",
  "💂": "guard",
  "💂‍♀️": "woman guard",
  "💂‍♂️": "man guard",
  "💃": "woman dancing",
  "💆": "person getting massage",
  "💆‍♀️": "woman getting massage",
  "💆‍♂️": "man getting massage",
  "💇": "person getting haircut",
  "💇‍♀️": "woman getting haircut",
  "💇‍♂️": "man getting haircut",
  "💏": "kiss",
  "💑": "couple with heart",
  "💪": "flexed biceps",
  "🕴": "person in suit levitating",
  "🕵": "detective",
  "🕵️‍♀️": "woman detective",
  "🕵️‍♂️": "man detective",
  "🕺": "man dancing",
  "🗣": "speaking head",
  "🙅": "person gesturing NO",
  "🙅‍♀️": "woman gesturing NO",
  "🙅‍♂️": "man gesturing NO",
  "🙆": "person gesturing OK",
  "🙆‍♀️": "woman gesturing OK",
  "🙆‍♂️": "man gesturing OK",
  "🙇": "person bowing",
  "🙇‍♀️": "woman bowing",
  "🙇‍♂️": "man bowing",
  "🙋": "person raising hand",
  "🙋‍♀️": "woman raising hand",
  "🙋‍♂️": "man raising hand",
  "🙍": "person frowning",
  "🙍‍♀️": "woman frowning",
  "🙍‍♂️": "man frowning",
  "🙎": "person pouting",
  "🙎‍♀️": "woman pouting",
  "🙎‍♂️": "man pouting",
  "🚣": "person rowing boat",
  "🚣‍♀️": "woman rowing boat",
  "🚣‍♂️": "man rowing boat",
  "🚴": "person biking",
  "🚴‍♀️": "woman biking",
  "🚴‍♂️": "man biking",
  "🚵": "person mountain biking",
  "🚵‍♀️": "woman mountain biking",
  "🚵‍♂️": "man mountain biking",
  "🚶": "person walking",
  "🚶‍♀️": "woman walking",
  "🚶‍♂️": "man walking",
  "🛀": "person taking bath",
  "🛌": "person in bed",
  "🤦": "person facepalming",
  "🤦‍♀️": "woman facepalming",
  "🤦‍♂️": "man facepalming",
  "🤰": "pregnant woman",
  "🤱": "breast-feeding",
  "🤴": "prince",
  "🤵": "person in tuxedo",
  "🤵‍♀️": "⊛ woman in tuxedo",
  "🤵‍♂️": "⊛ man in tuxedo",
  "🤶": "Mrs. Claus",
  "🤷": "person shrugging",
  "🤷‍♀️": "woman shrugging",
  "🤷‍♂️": "man shrugging",
  "🤸": "person cartwheeling",
  "🤸‍♀️": "woman cartwheeling",
  "🤸‍♂️": "man cartwheeling",
  "🤹": "person juggling",
  "🤹‍♀️": "woman juggling",
  "🤹‍♂️": "man juggling",
  "🤺": "person fencing",
  "🤼": "people wrestling",
  "🤼‍♀️": "women wrestling",
  "🤼‍♂️": "men wrestling",
  "🤽": "person playing water polo",
  "🤽‍♀️": "woman playing water polo",
  "🤽‍♂️": "man playing water polo",
  "🤾": "person playing handball",
  "🤾‍♀️": "woman playing handball",
  "🤾‍♂️": "man playing handball",
  "🥷": "⊛ ninja",
  "🦴": "bone",
  "🦵": "leg",
  "🦶": "foot",
  "🦷": "tooth",
  "🦸": "superhero",
  "🦸‍♀️": "woman superhero",
  "🦸‍♂️": "man superhero",
  "🦹": "supervillain",
  "🦹‍♀️": "woman supervillain",
  "🦹‍♂️": "man supervillain",
  "🦻": "ear with hearing aid",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🧍": "person standing",
  "🧍‍♀️": "woman standing",
  "🧍‍♂️": "man standing",
  "🧎": "person kneeling",
  "🧎‍♀️": "woman kneeling",
  "🧎‍♂️": "man kneeling",
  "🧏": "deaf person",
  "🧏‍♀️": "deaf woman",
  "🧏‍♂️": "deaf man",
  "🧑": "person",
  "🧑‍⚕️": "health worker",
  "🧑‍⚖️": "judge",
  "🧑‍✈️": "pilot",
  "🧑‍🌾": "farmer",
  "🧑‍🍳": "cook",
  "🧑‍🍼": "⊛ person feeding baby",
  "🧑‍🎄": "⊛ mx claus",
  "🧑‍🎓": "student",
  "🧑‍🎤": "singer",
  "🧑‍🎨": "artist",
  "🧑‍🏫": "teacher",
  "🧑‍🏭": "factory worker",
  "🧑‍💻": "technologist",
  "🧑‍💼": "office worker",
  "🧑‍🔧": "mechanic",
  "🧑‍🔬": "scientist",
  "🧑‍🚀": "astronaut",
  "🧑‍🚒": "firefighter",
  "🧑‍🤝‍🧑": "people holding hands",
  "🧑‍🦯": "person with white cane",
  "🧑‍🦰": "person: red hair",
  "🧑‍🦱": "person: curly hair",
  "🧑‍🦲": "person: bald",
  "🧑‍🦳": "person: white hair",
  "🧑‍🦼": "person in motorized wheelchair",
  "🧑‍🦽": "person in manual wheelchair",
  "🧒": "child",
  "🧓": "older person",
  "🧔": "man: beard",
  "🧕": "woman with headscarf",
  "🧖": "person in steamy room",
  "🧖‍♀️": "woman in steamy room",
  "🧖‍♂️": "man in steamy room",
  "🧗": "person climbing",
  "🧗‍♀️": "woman climbing",
  "🧗‍♂️": "man climbing",
  "🧘": "person in lotus position",
  "🧘‍♀️": "woman in lotus position",
  "🧘‍♂️": "man in lotus position",
  "🧙": "mage",
  "🧙‍♀️": "woman mage",
  "🧙‍♂️": "man mage",
  "🧚": "fairy",
  "🧚‍♀️": "woman fairy",
  "🧚‍♂️": "man fairy",
  "🧛": "vampire",
  "🧛‍♀️": "woman vampire",
  "🧛‍♂️": "man vampire",
  "🧜": "merperson",
  "🧜‍♀️": "mermaid",
  "🧜‍♂️": "merman",
  "🧝": "elf",
  "🧝‍♀️": "woman elf",
  "🧝‍♂️": "man elf",
  "🧞": "genie",
  "🧞‍♀️": "woman genie",
  "🧞‍♂️": "man genie",
  "🧟": "zombie",
  "🧟‍♀️": "woman zombie",
  "🧟‍♂️": "man zombie",
  "🧠": "brain",
  "🫀": "⊛ anatomical heart",
  "🫁": "⊛ lungs",
  "🫂": "⊛ people hugging",
  "✊": "raised fist",
  "✍": "writing hand",
  "👊": "oncoming fist",
  "👍": "thumbs up",
  "👎": "thumbs down",
  "👏": "clapping hands",
  "👐": "open hands",
  "💅": "nail polish",
  "🙌": "raising hands",
  "🙏": "folded hands",
  "🤛": "left-facing fist",
  "🤜": "right-facing fist",
  "🤝": "handshake",
  "🤲": "palms up together",
  "🤳": "selfie",
  "☝": "index pointing up",
  "✋": "raised hand",
  "✌": "victory hand",
  "👆": "backhand index pointing up",
  "👇": "backhand index pointing down",
  "👈": "backhand index pointing left",
  "👉": "backhand index pointing right",
  "👋": "waving hand",
  "👌": "OK hand",
  "🖐": "hand with fingers splayed",
  "🖕": "middle finger",
  "🖖": "vulcan salute",
  "🤌": "⊛ pinched fingers",
  "🤏": "pinching hand",
  "🤘": "sign of the horns",
  "🤙": "call me hand",
  "🤚": "raised back of hand",
  "🤞": "crossed fingers",
  "🤟": "love-you gesture",
  "❣": "heart exclamation",
  "❤": "red heart",
  "👁️‍🗨️": "eye in speech bubble",
  "💋": "kiss mark",
  "💌": "love letter",
  "💓": "beating heart",
  "💔": "broken heart",
  "💕": "two hearts",
  "💖": "sparkling heart",
  "💗": "growing heart",
  "💘": "heart with arrow",
  "💙": "blue heart",
  "💚": "green heart",
  "💛": "yellow heart",
  "💜": "purple heart",
  "💝": "heart with ribbon",
  "💞": "revolving hearts",
  "💟": "heart decoration",
  "💢": "anger symbol",
  "💣": "bomb",
  "💤": "zzz",
  "💥": "collision",
  "💦": "sweat droplets",
  "💨": "dashing away",
  "💫": "dizzy",
  "💬": "speech balloon",
  "💭": "thought balloon",
  "💯": "hundred points",
  "🕳": "hole",
  "🖤": "black heart",
  "🗨": "left speech bubble",
  "🗯": "right anger bubble",
  "😸": "grinning cat with smiling eyes",
  "😹": "cat with tears of joy",
  "😺": "grinning cat",
  "😻": "smiling cat with heart-eyes",
  "😼": "cat with wry smile",
  "😽": "kissing cat",
  "😾": "pouting cat",
  "😿": "crying cat",
  "🙀": "weary cat",
  "🙈": "see-no-evil monkey",
  "🙉": "hear-no-evil monkey",
  "🙊": "speak-no-evil monkey",
  "🤍": "white heart",
  "🤎": "brown heart",
  "🧡": "orange heart",
  "☠": "skull and crossbones",
  "☹": "frowning face",
  "☺": "smiling face",
  "👹": "ogre",
  "👺": "goblin",
  "👻": "ghost",
  "👽": "alien",
  "👾": "alien monster",
  "👿": "angry face with horns",
  "💀": "skull",
  "💩": "pile of poo",
  "😈": "smiling face with horns",
  "😋": "face savoring food",
  "😌": "relieved face",
  "😍": "smiling face with heart-eyes",
  "😎": "smiling face with sunglasses",
  "😏": "smirking face",
  "😐": "neutral face",
  "😑": "expressionless face",
  "😒": "unamused face",
  "😓": "downcast face with sweat",
  "😔": "pensive face",
  "😕": "confused face",
  "😖": "confounded face",
  "😗": "kissing face",
  "😘": "face blowing a kiss",
  "😙": "kissing face with smiling eyes",
  "😚": "kissing face with closed eyes",
  "😛": "face with tongue",
  "😜": "winking face with tongue",
  "😝": "squinting face with tongue",
  "😞": "disappointed face",
  "😟": "worried face",
  "😠": "angry face",
  "😡": "pouting face",
  "😢": "crying face",
  "😣": "persevering face",
  "😤": "face with steam from nose",
  "😥": "sad but relieved face",
  "😦": "frowning face with open mouth",
  "😧": "anguished face",
  "😨": "fearful face",
  "😩": "weary face",
  "😪": "sleepy face",
  "😫": "tired face",
  "😬": "grimacing face",
  "😭": "loudly crying face",
  "😮": "face with open mouth",
  "😯": "hushed face",
  "😰": "anxious face with sweat",
  "😱": "face screaming in fear",
  "😲": "astonished face",
  "😳": "flushed face",
  "😴": "sleeping face",
  "😵": "dizzy face",
  "😶": "face without mouth",
  "😷": "face with medical mask",
  "🙁": "slightly frowning face",
  "🙄": "face with rolling eyes",
  "🤐": "zipper-mouth face",
  "🤑": "money-mouth face",
  "🤒": "face with thermometer",
  "🤓": "nerd face",
  "🤔": "thinking face",
  "🤕": "face with head-bandage",
  "🤖": "robot",
  "🤗": "hugging face",
  "🤠": "cowboy hat face",
  "🤡": "clown face",
  "🤢": "nauseated face",
  "🤤": "drooling face",
  "🤥": "lying face",
  "🤧": "sneezing face",
  "🤨": "face with raised eyebrow",
  "🤩": "star-struck",
  "🤪": "zany face",
  "🤫": "shushing face",
  "🤬": "face with symbols on mouth",
  "🤭": "face with hand over mouth",
  "🤮": "face vomiting",
  "🤯": "exploding head",
  "🥰": "smiling face with hearts",
  "🥱": "yawning face",
  "🥲": "⊛ smiling face with tear",
  "🥳": "partying face",
  "🥴": "woozy face",
  "🥵": "hot face",
  "🥶": "cold face",
  "🥸": "⊛ disguised face",
  "🥺": "pleading face",
  "🧐": "face with monocle",
  "😀": "grinning face",
  "😁": "beaming face with smiling eyes",
  "😂": "face with tears of joy",
  "😃": "grinning face with big eyes",
  "😄": "grinning face with smiling eyes",
  "😅": "grinning face with sweat",
  "😆": "grinning squinting face",
  "😇": "smiling face with halo",
  "😉": "winking face",
  "😊": "smiling face with smiling eyes",
  "🙂": "slightly smiling face",
  "🙃": "upside-down face",
  "🤣": "rolling on the floor laughing",
  "ℹ": "information",
  "Ⓜ": "circled M",
  "▪": "black small square",
  "▫": "white small square",
  "◻": "white medium square",
  "◼": "black medium square",
  "◽": "white medium-small square",
  "◾": "black medium-small square",
  "⚪": "white circle",
  "⚫": "black circle",
  "⬛": "black large square",
  "⬜": "white large square",
  "㊗": "Japanese “congratulations” button",
  "㊙": "Japanese “secret” button",
  "🅰": "A button (blood type)",
  "🅱": "B button (blood type)",
  "🅾": "O button (blood type)",
  "🅿": "P button",
  "🆎": "AB button (blood type)",
  "🆑": "CL button",
  "🆒": "COOL button",
  "🆓": "FREE button",
  "🆔": "ID button",
  "🆕": "NEW button",
  "🆖": "NG button",
  "🆗": "OK button",
  "🆘": "SOS button",
  "🆙": "UP! button",
  "🆚": "VS button",
  "🈁": "Japanese “here” button",
  "🈂": "Japanese “service charge” button",
  "🈚": "Japanese “free of charge” button",
  "🈯": "Japanese “reserved” button",
  "🈲": "Japanese “prohibited” button",
  "🈳": "Japanese “vacancy” button",
  "🈴": "Japanese “passing grade” button",
  "🈵": "Japanese “no vacancy” button",
  "🈶": "Japanese “not free of charge” button",
  "🈷": "Japanese “monthly amount” button",
  "🈸": "Japanese “application” button",
  "🈹": "Japanese “discount” button",
  "🈺": "Japanese “open for business” button",
  "🉐": "Japanese “bargain” button",
  "🉑": "Japanese “acceptable” button",
  "💠": "diamond with a dot",
  "🔘": "radio button",
  "🔠": "input latin uppercase",
  "🔡": "input latin lowercase",
  "🔢": "input numbers",
  "🔣": "input symbols",
  "🔤": "input latin letters",
  "🔲": "black square button",
  "🔳": "white square button",
  "🔴": "red circle",
  "🔵": "blue circle",
  "🔶": "large orange diamond",
  "🔷": "large blue diamond",
  "🔸": "small orange diamond",
  "🔹": "small blue diamond",
  "🔺": "red triangle pointed up",
  "🔻": "red triangle pointed down",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🟣": "purple circle",
  "🟤": "brown circle",
  "🟥": "red square",
  "🟦": "blue square",
  "🟧": "orange square",
  "🟨": "yellow square",
  "🟩": "green square",
  "🟪": "purple square",
  "🟫": "brown square",
  "#️⃣": "keycap: #",
  "*️⃣": "keycap: *",
  "0️⃣": "keycap: 0",
  "1️⃣": "keycap: 1",
  "2️⃣": "keycap: 2",
  "3️⃣": "keycap: 3",
  "4️⃣": "keycap: 4",
  "5️⃣": "keycap: 5",
  "6️⃣": "keycap: 6",
  "7️⃣": "keycap: 7",
  "8️⃣": "keycap: 8",
  "9️⃣": "keycap: 9",
  "©": "copyright",
  "®": "registered",
  "‼": "double exclamation mark",
  "⁉": "exclamation question mark",
  "™": "trade mark",
  "↔": "left-right arrow",
  "↕": "up-down arrow",
  "↖": "up-left arrow",
  "↗": "up-right arrow",
  "↘": "down-right arrow",
  "↙": "down-left arrow",
  "↩": "right arrow curving left",
  "↪": "left arrow curving right",
  "⏏": "eject button",
  "⏩": "fast-forward button",
  "⏪": "fast reverse button",
  "⏫": "fast up button",
  "⏬": "fast down button",
  "⏭": "next track button",
  "⏮": "last track button",
  "⏯": "play or pause button",
  "⏸": "pause button",
  "⏹": "stop button",
  "⏺": "record button",
  "▶": "play button",
  "◀": "reverse button",
  "☑": "check box with check",
  "☦": "orthodox cross",
  "☪": "star and crescent",
  "☮": "peace symbol",
  "☯": "yin yang",
  "☸": "wheel of dharma",
  "♀": "female sign",
  "♂": "male sign",
  "♈": "Aries",
  "♉": "Taurus",
  "♊": "Gemini",
  "♋": "Cancer",
  "♌": "Leo",
  "♍": "Virgo",
  "♎": "Libra",
  "♏": "Scorpio",
  "♐": "Sagittarius",
  "♑": "Capricorn",
  "♒": "Aquarius",
  "♓": "Pisces",
  "♻": "recycling symbol",
  "♾": "infinity",
  "⚕": "medical symbol",
  "⚛": "atom symbol",
  "⚜": "fleur-de-lis",
  "⚧": "⊛ transgender symbol",
  "⛎": "Ophiuchus",
  "✅": "check mark button",
  "✔": "check mark",
  "✖": "multiply",
  "✝": "latin cross",
  "✡": "star of David",
  "✳": "eight-spoked asterisk",
  "✴": "eight-pointed star",
  "❇": "sparkle",
  "❌": "cross mark",
  "❎": "cross mark button",
  "❓": "question mark",
  "❔": "white question mark",
  "❕": "white exclamation mark",
  "❗": "exclamation mark",
  "➕": "plus",
  "➖": "minus",
  "➗": "divide",
  "➡": "right arrow",
  "➰": "curly loop",
  "➿": "double curly loop",
  "⤴": "right arrow curving up",
  "⤵": "right arrow curving down",
  "⬅": "left arrow",
  "⬆": "up arrow",
  "⬇": "down arrow",
  "⭕": "hollow red circle",
  "〰": "wavy dash",
  "〽": "part alternation mark",
  "🎦": "cinema",
  "💱": "currency exchange",
  "💲": "heavy dollar sign",
  "📛": "name badge",
  "📳": "vibration mode",
  "📴": "mobile phone off",
  "📶": "antenna bars",
  "🔀": "shuffle tracks button",
  "🔁": "repeat button",
  "🔂": "repeat single button",
  "🔃": "clockwise vertical arrows",
  "🔄": "counterclockwise arrows button",
  "🔅": "dim button",
  "🔆": "bright button",
  "🔙": "BACK arrow",
  "🔚": "END arrow",
  "🔛": "ON! arrow",
  "🔜": "SOON arrow",
  "🔝": "TOP arrow",
  "🔟": "keycap: 10",
  "🔯": "dotted six-pointed star",
  "🔰": "Japanese symbol for beginner",
  "🔱": "trident emblem",
  "🔼": "upwards button",
  "🔽": "downwards button",
  "🕉": "om",
  "🕎": "menorah",
  "🛐": "place of worship",
  "☢": "radioactive",
  "☣": "biohazard",
  "♿": "wheelchair symbol",
  "⚠": "warning",
  "⛔": "no entry",
  "🏧": "ATM sign",
  "📵": "no mobile phones",
  "🔞": "no one under eighteen",
  "🚫": "prohibited",
  "🚭": "no smoking",
  "🚮": "litter in bin sign",
  "🚯": "no littering",
  "🚰": "potable water",
  "🚱": "non-potable water",
  "🚳": "no bicycles",
  "🚷": "no pedestrians",
  "🚸": "children crossing",
  "🚹": "men’s room",
  "🚺": "women’s room",
  "🚻": "restroom",
  "🚼": "baby symbol",
  "🚾": "water closet",
  "🛂": "passport control",
  "🛃": "customs",
  "🛄": "baggage claim",
  "🛅": "left luggage",
  "⌚": "watch",
  "⌛": "hourglass done",
  "⏰": "alarm clock",
  "⏱": "stopwatch",
  "⏲": "timer clock",
  "⏳": "hourglass not done",
  "☀": "sun",
  "☁": "cloud",
  "☂": "umbrella",
  "☃": "snowman",
  "☄": "comet",
  "☔": "umbrella with rain drops",
  "⚡": "high voltage",
  "⛄": "snowman without snow",
  "⛅": "sun behind cloud",
  "⛈": "cloud with lightning and rain",
  "⛱": "umbrella on ground",
  "❄": "snowflake",
  "⭐": "star",
  "🌀": "cyclone",
  "🌂": "closed umbrella",
  "🌈": "rainbow",
  "🌊": "water wave",
  "🌌": "milky way",
  "🌑": "new moon",
  "🌒": "waxing crescent moon",
  "🌓": "first quarter moon",
  "🌔": "waxing gibbous moon",
  "🌕": "full moon",
  "🌖": "waning gibbous moon",
  "🌗": "last quarter moon",
  "🌘": "waning crescent moon",
  "🌙": "crescent moon",
  "🌚": "new moon face",
  "🌛": "first quarter moon face",
  "🌜": "last quarter moon face",
  "🌝": "full moon face",
  "🌞": "sun with face",
  "🌟": "glowing star",
  "🌠": "shooting star",
  "🌡": "thermometer",
  "🌤": "sun behind small cloud",
  "🌥": "sun behind large cloud",
  "🌦": "sun behind rain cloud",
  "🌧": "cloud with rain",
  "🌨": "cloud with snow",
  "🌩": "cloud with lightning",
  "🌪": "tornado",
  "🌫": "fog",
  "🌬": "wind face",
  "💧": "droplet",
  "🔥": "fire",
  "🕐": "one o’clock",
  "🕑": "two o’clock",
  "🕒": "three o’clock",
  "🕓": "four o’clock",
  "🕔": "five o’clock",
  "🕕": "six o’clock",
  "🕖": "seven o’clock",
  "🕗": "eight o’clock",
  "🕘": "nine o’clock",
  "🕙": "ten o’clock",
  "🕚": "eleven o’clock",
  "🕛": "twelve o’clock",
  "🕜": "one-thirty",
  "🕝": "two-thirty",
  "🕞": "three-thirty",
  "🕟": "four-thirty",
  "🕠": "five-thirty",
  "🕡": "six-thirty",
  "🕢": "seven-thirty",
  "🕣": "eight-thirty",
  "🕤": "nine-thirty",
  "🕥": "ten-thirty",
  "🕦": "eleven-thirty",
  "🕧": "twelve-thirty",
  "🕰": "mantelpiece clock",
  "🛎": "bellhop bell",
  "🧳": "luggage",
  "🪐": "ringed planet",
  "♨": "hot springs",
  "⚓": "anchor",
  "⛩": "shinto shrine",
  "⛪": "church",
  "⛲": "fountain",
  "⛴": "ferry",
  "⛵": "sailboat",
  "⛺": "tent",
  "⛽": "fuel pump",
  "✈": "airplane",
  "🌁": "foggy",
  "🌃": "night with stars",
  "🌄": "sunrise over mountains",
  "🌅": "sunrise",
  "🌆": "cityscape at dusk",
  "🌇": "sunset",
  "🌉": "bridge at night",
  "🎠": "carousel horse",
  "🎡": "ferris wheel",
  "🎢": "roller coaster",
  "🎪": "circus tent",
  "🏍": "motorcycle",
  "🏎": "racing car",
  "🏗": "building construction",
  "🏘": "houses",
  "🏙": "cityscape",
  "🏚": "derelict house",
  "🏛": "classical building",
  "🏟": "stadium",
  "🏠": "house",
  "🏡": "house with garden",
  "🏢": "office building",
  "🏣": "Japanese post office",
  "🏤": "post office",
  "🏥": "hospital",
  "🏦": "bank",
  "🏨": "hotel",
  "🏩": "love hotel",
  "🏪": "convenience store",
  "🏫": "school",
  "🏬": "department store",
  "🏭": "factory",
  "🏯": "Japanese castle",
  "🏰": "castle",
  "💈": "barber pole",
  "💒": "wedding",
  "💺": "seat",
  "🕋": "kaaba",
  "🕌": "mosque",
  "🕍": "synagogue",
  "🗼": "Tokyo tower",
  "🗽": "Statue of Liberty",
  "🚀": "rocket",
  "🚁": "helicopter",
  "🚂": "locomotive",
  "🚃": "railway car",
  "🚄": "high-speed train",
  "🚅": "bullet train",
  "🚆": "train",
  "🚇": "metro",
  "🚈": "light rail",
  "🚉": "station",
  "🚊": "tram",
  "🚋": "tram car",
  "🚌": "bus",
  "🚍": "oncoming bus",
  "🚎": "trolleybus",
  "🚏": "bus stop",
  "🚐": "minibus",
  "🚑": "ambulance",
  "🚒": "fire engine",
  "🚓": "police car",
  "🚔": "oncoming police car",
  "🚕": "taxi",
  "🚖": "oncoming taxi",
  "🚗": "automobile",
  "🚘": "oncoming automobile",
  "🚙": "sport utility vehicle",
  "🚚": "delivery truck",
  "🚛": "articulated lorry",
  "🚜": "tractor",
  "🚝": "monorail",
  "🚞": "mountain railway",
  "🚟": "suspension railway",
  "🚠": "mountain cableway",
  "🚡": "aerial tramway",
  "🚢": "ship",
  "🚤": "speedboat",
  "🚥": "horizontal traffic light",
  "🚦": "vertical traffic light",
  "🚧": "construction",
  "🚨": "police car light",
  "🚲": "bicycle",
  "🛑": "stop sign",
  "🛕": "hindu temple",
  "🛖": "⊛ hut",
  "🛢": "oil drum",
  "🛣": "motorway",
  "🛤": "railway track",
  "🛥": "motor boat",
  "🛩": "small airplane",
  "🛫": "airplane departure",
  "🛬": "airplane arrival",
  "🛰": "satellite",
  "🛳": "passenger ship",
  "🛴": "kick scooter",
  "🛵": "motor scooter",
  "🛶": "canoe",
  "🛸": "flying saucer",
  "🛹": "skateboard",
  "🛺": "auto rickshaw",
  "🛻": "⊛ pickup truck",
  "🛼": "⊛ roller skate",
  "🦼": "motorized wheelchair",
  "🦽": "manual wheelchair",
  "🧱": "brick",
  "🪂": "parachute",
  "🪨": "⊛ rock",
  "🪵": "⊛ wood",
  "⛰": "mountain",
  "🌋": "volcano",
  "🏔": "snow-capped mountain",
  "🏕": "camping",
  "🏖": "beach with umbrella",
  "🏜": "desert",
  "🏝": "desert island",
  "🏞": "national park",
  "🗻": "mount fuji",
  "🌍": "globe showing Europe-Africa",
  "🌎": "globe showing Americas",
  "🌏": "globe showing Asia-Australia",
  "🌐": "globe with meridians",
  "🗺": "world map",
  "🗾": "map of Japan",
  "🧭": "compass"
};
